project_id = "bylxzpvyzvycrpkwxvle"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public", "supabase_functions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[functions.kommo-status-webhook]
verify_jwt = false
